# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pilot_homepage.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 788)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 788))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 788))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 971, 721))
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mission = QtWidgets.QWidget()
        self.tab_mission.setObjectName("tab_mission")
        self.tbr_coordinates = QtWidgets.QTextBrowser(self.tab_mission)
        self.tbr_coordinates.setGeometry(QtCore.QRect(710, 50, 251, 551))
        self.tbr_coordinates.setObjectName("tbr_coordinates")
        self.web_drone_map = QtWebEngineWidgets.QWebEngineView(self.tab_mission)
        self.web_drone_map.setGeometry(QtCore.QRect(10, 10, 691, 671))
        self.web_drone_map.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.web_drone_map.setObjectName("web_drone_map")
        self.btn_clear_coordinates = QtWidgets.QPushButton(self.tab_mission)
        self.btn_clear_coordinates.setGeometry(QtCore.QRect(840, 610, 121, 31))
        self.btn_clear_coordinates.setObjectName("btn_clear_coordinates")
        self.btn_undo_coordinate = QtWidgets.QPushButton(self.tab_mission)
        self.btn_undo_coordinate.setGeometry(QtCore.QRect(710, 610, 121, 31))
        self.btn_undo_coordinate.setObjectName("btn_undo_coordinate")
        self.btn_clear_coordinates_3 = QtWidgets.QPushButton(self.tab_mission)
        self.btn_clear_coordinates_3.setGeometry(QtCore.QRect(710, 650, 251, 31))
        self.btn_clear_coordinates_3.setObjectName("btn_clear_coordinates_3")
        self.btn_save_path_file = QtWidgets.QPushButton(self.tab_mission)
        self.btn_save_path_file.setGeometry(QtCore.QRect(710, 10, 121, 31))
        self.btn_save_path_file.setObjectName("btn_save_path_file")
        self.btn_open_path_file = QtWidgets.QPushButton(self.tab_mission)
        self.btn_open_path_file.setGeometry(QtCore.QRect(840, 10, 121, 31))
        self.btn_open_path_file.setObjectName("btn_open_path_file")
        self.tabWidget.addTab(self.tab_mission, "")
        self.tab_drone_stream = QtWidgets.QWidget()
        self.tab_drone_stream.setObjectName("tab_drone_stream")
        self.drone_stream_2 = QtWidgets.QLabel(self.tab_drone_stream)
        self.drone_stream_2.setGeometry(QtCore.QRect(60, 10, 856, 480))
        self.drone_stream_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.drone_stream_2.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.drone_stream_2.setObjectName("drone_stream_2")
        self.btn_terminate_mission = QtWidgets.QPushButton(self.tab_drone_stream)
        self.btn_terminate_mission.setGeometry(QtCore.QRect(600, 570, 321, 51))
        self.btn_terminate_mission.setObjectName("btn_terminate_mission")
        self.tbr_mission_log = QtWidgets.QTextBrowser(self.tab_drone_stream)
        self.tbr_mission_log.setGeometry(QtCore.QRect(60, 500, 531, 181))
        self.tbr_mission_log.setObjectName("tbr_mission_log")
        self.btn_save_mission_log = QtWidgets.QPushButton(self.tab_drone_stream)
        self.btn_save_mission_log.setGeometry(QtCore.QRect(600, 630, 321, 51))
        self.btn_save_mission_log.setObjectName("btn_save_mission_log")
        self.toolButton = QtWidgets.QToolButton(self.tab_drone_stream)
        self.toolButton.setGeometry(QtCore.QRect(600, 500, 321, 61))
        self.toolButton.setObjectName("toolButton")
        self.tabWidget.addTab(self.tab_drone_stream, "")
        self.tbr_console_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbr_console_output.setGeometry(QtCore.QRect(1000, 90, 351, 671))
        font = QtGui.QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(12)
        self.tbr_console_output.setFont(font)
        self.tbr_console_output.setObjectName("tbr_console_output")
        self.btn_view_profile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_view_profile.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.btn_view_profile.setObjectName("btn_view_profile")
        self.bnt_past_operations = QtWidgets.QPushButton(self.centralwidget)
        self.bnt_past_operations.setGeometry(QtCore.QRect(190, 10, 161, 31))
        self.bnt_past_operations.setObjectName("bnt_past_operations")
        self.btn_log_out = QtWidgets.QPushButton(self.centralwidget)
        self.btn_log_out.setGeometry(QtCore.QRect(1000, 10, 161, 31))
        self.btn_log_out.setObjectName("btn_log_out")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSAVE = QtWidgets.QAction(MainWindow)
        self.actionSAVE.setObjectName("actionSAVE")
        self.actionPERHAPS = QtWidgets.QAction(MainWindow)
        self.actionPERHAPS.setObjectName("actionPERHAPS")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_clear_coordinates.setText(_translate("MainWindow", "Reset"))
        self.btn_undo_coordinate.setText(_translate("MainWindow", "Undo"))
        self.btn_clear_coordinates_3.setText(_translate("MainWindow", "CONFIRM MISSION"))
        self.btn_save_path_file.setText(_translate("MainWindow", "Save Path"))
        self.btn_open_path_file.setText(_translate("MainWindow", "Open Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mission), _translate("MainWindow", "Mission"))
        self.drone_stream_2.setText(_translate("MainWindow", "DRONE STREAM"))
        self.btn_terminate_mission.setText(_translate("MainWindow", "Terminate Mission"))
        self.btn_save_mission_log.setText(_translate("MainWindow", "Save Mission Log"))
        self.toolButton.setText(_translate("MainWindow", "Launch Drone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_drone_stream), _translate("MainWindow", "Drone Stream"))
        self.tbr_console_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Code Retina\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mission Report:</p></body></html>"))
        self.btn_view_profile.setText(_translate("MainWindow", "View Profile"))
        self.bnt_past_operations.setText(_translate("MainWindow", "Past Operations"))
        self.btn_log_out.setText(_translate("MainWindow", "Log Out"))
        self.actionSAVE.setText(_translate("MainWindow", "SAVE"))
        self.actionPERHAPS.setText(_translate("MainWindow", "PERHAPS"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())