# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewPilotAlt.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 739)
        MainWindow.setMinimumSize(QtCore.QSize(1071, 739))
        MainWindow.setMaximumSize(QtCore.QSize(1071, 739))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Resources/logo_svg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_addPilot = QtWidgets.QLabel(self.centralwidget)
        self.lbl_addPilot.setGeometry(QtCore.QRect(30, 50, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(29)
        font.setKerning(True)
        self.lbl_addPilot.setFont(font)
        self.lbl_addPilot.setStyleSheet("\n"
"")
        self.lbl_addPilot.setText("")
        self.lbl_addPilot.setObjectName("lbl_addPilot")
        self.lbl_caap = QtWidgets.QLabel(self.centralwidget)
        self.lbl_caap.setGeometry(QtCore.QRect(20, 520, 381, 35))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(19)
        font.setKerning(True)
        self.lbl_caap.setFont(font)
        self.lbl_caap.setStyleSheet("padding-left:3px;")
        self.lbl_caap.setObjectName("lbl_caap")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 220, 761, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 500, 771, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 360, 761, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lbl_profilePic = QtWidgets.QLabel(self.centralwidget)
        self.lbl_profilePic.setGeometry(QtCore.QRect(830, 30, 191, 181))
        self.lbl_profilePic.setMinimumSize(QtCore.QSize(191, 181))
        self.lbl_profilePic.setMaximumSize(QtCore.QSize(191, 181))
        self.lbl_profilePic.setText("")
        self.lbl_profilePic.setPixmap(QtGui.QPixmap("../../Resources/profile_placeholder.png"))
        self.lbl_profilePic.setScaledContents(True)
        self.lbl_profilePic.setObjectName("lbl_profilePic")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(606, 682, 441, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.btn_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.btn_layout.setContentsMargins(0, 0, 0, 0)
        self.btn_layout.setObjectName("btn_layout")
        self.btn_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_cancel.setMinimumSize(QtCore.QSize(131, 31))
        self.btn_cancel.setMaximumSize(QtCore.QSize(131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(202, 202, 202);\n"
"border: 1.2px solid #ABABAB;\n"
"outline: none;}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(171, 171, 171);\n"
"outline: none;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(129, 129, 129);\n"
"outline: none;\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_layout.addWidget(self.btn_cancel)
        self.btn_pastops = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_pastops.setMinimumSize(QtCore.QSize(131, 31))
        self.btn_pastops.setMaximumSize(QtCore.QSize(131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.btn_pastops.setFont(font)
        self.btn_pastops.setStyleSheet("QPushButton {\n"
"background-color: rgb(70, 186, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 1.4px solid #39A0ee;\n"
"outline: none;}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(60, 175, 253);\n"
"outline: none;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"background-color: rgb(53, 141, 217);\n"
"outline: none;\n"
"border: none;\n"
"}\n"
"")
        self.btn_pastops.setObjectName("btn_pastops")
        self.btn_layout.addWidget(self.btn_pastops)
        self.btn_update = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_update.setMinimumSize(QtCore.QSize(131, 31))
        self.btn_update.setMaximumSize(QtCore.QSize(131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.btn_update.setFont(font)
        self.btn_update.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 176, 6);\n"
"border: 1.2px solid #ff9d07;\n"
"outline: none;}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 157, 7);\n"
"outline: none;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(254, 140, 8);\n"
"outline: none;\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.btn_update.setObjectName("btn_update")
        self.btn_layout.addWidget(self.btn_update)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(320, 630, 241, 33))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.expirydate_layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.expirydate_layout.setContentsMargins(0, 0, 0, 0)
        self.expirydate_layout.setObjectName("expirydate_layout")
        self.lbl_expirydate_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_expirydate_2.setFont(font)
        self.lbl_expirydate_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_expirydate_2.setObjectName("lbl_expirydate_2")
        self.expirydate_layout.addWidget(self.lbl_expirydate_2)
        self.lbl_expirydate = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_expirydate.setMinimumSize(QtCore.QSize(81, 31))
        self.lbl_expirydate.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_expirydate.setFont(font)
        self.lbl_expirydate.setText("")
        self.lbl_expirydate.setObjectName("lbl_expirydate")
        self.expirydate_layout.addWidget(self.lbl_expirydate)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 180, 171, 33))
        self.widget.setObjectName("widget")
        self.gender_layout = QtWidgets.QHBoxLayout(self.widget)
        self.gender_layout.setContentsMargins(0, 0, 0, 0)
        self.gender_layout.setObjectName("gender_layout")
        self.lbl_gender_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_gender_2.setFont(font)
        self.lbl_gender_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_gender_2.setObjectName("lbl_gender_2")
        self.gender_layout.addWidget(self.lbl_gender_2)
        self.lbl_gender = QtWidgets.QLabel(self.widget)
        self.lbl_gender.setMinimumSize(QtCore.QSize(81, 31))
        self.lbl_gender.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_gender.setFont(font)
        self.lbl_gender.setText("")
        self.lbl_gender.setObjectName("lbl_gender")
        self.gender_layout.addWidget(self.lbl_gender)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 250, 681, 33))
        self.widget1.setObjectName("widget1")
        self.address_layout = QtWidgets.QHBoxLayout(self.widget1)
        self.address_layout.setContentsMargins(0, 0, 0, 0)
        self.address_layout.setObjectName("address_layout")
        self.lbl_address_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_address_2.setFont(font)
        self.lbl_address_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_address_2.setObjectName("lbl_address_2")
        self.address_layout.addWidget(self.lbl_address_2)
        self.lbl_address = QtWidgets.QLabel(self.widget1)
        self.lbl_address.setMinimumSize(QtCore.QSize(491, 31))
        self.lbl_address.setMaximumSize(QtCore.QSize(491, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_address.setFont(font)
        self.lbl_address.setText("")
        self.lbl_address.setObjectName("lbl_address")
        self.address_layout.addWidget(self.lbl_address)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(30, 310, 201, 33))
        self.widget2.setObjectName("widget2")
        self.city_layout = QtWidgets.QHBoxLayout(self.widget2)
        self.city_layout.setContentsMargins(0, 0, 0, 0)
        self.city_layout.setObjectName("city_layout")
        self.lbl_city_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_city_2.setFont(font)
        self.lbl_city_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_city_2.setObjectName("lbl_city_2")
        self.city_layout.addWidget(self.lbl_city_2)
        self.lbl_city = QtWidgets.QLabel(self.widget2)
        self.lbl_city.setMinimumSize(QtCore.QSize(131, 31))
        self.lbl_city.setMaximumSize(QtCore.QSize(131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_city.setFont(font)
        self.lbl_city.setText("")
        self.lbl_city.setObjectName("lbl_city")
        self.city_layout.addWidget(self.lbl_city)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(260, 310, 241, 33))
        self.widget3.setObjectName("widget3")
        self.province_layout = QtWidgets.QHBoxLayout(self.widget3)
        self.province_layout.setContentsMargins(0, 0, 0, 0)
        self.province_layout.setObjectName("province_layout")
        self.lbl_province_2 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_province_2.setFont(font)
        self.lbl_province_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_province_2.setObjectName("lbl_province_2")
        self.province_layout.addWidget(self.lbl_province_2)
        self.lbl_province = QtWidgets.QLabel(self.widget3)
        self.lbl_province.setMinimumSize(QtCore.QSize(151, 31))
        self.lbl_province.setMaximumSize(QtCore.QSize(151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_province.setFont(font)
        self.lbl_province.setText("")
        self.lbl_province.setObjectName("lbl_province")
        self.province_layout.addWidget(self.lbl_province)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(530, 310, 181, 33))
        self.widget4.setObjectName("widget4")
        self.zip_layout = QtWidgets.QHBoxLayout(self.widget4)
        self.zip_layout.setContentsMargins(0, 0, 0, 0)
        self.zip_layout.setObjectName("zip_layout")
        self.lbl_zip_2 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_zip_2.setFont(font)
        self.lbl_zip_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_zip_2.setObjectName("lbl_zip_2")
        self.zip_layout.addWidget(self.lbl_zip_2)
        self.lbl_zip = QtWidgets.QLabel(self.widget4)
        self.lbl_zip.setMinimumSize(QtCore.QSize(91, 31))
        self.lbl_zip.setMaximumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_zip.setFont(font)
        self.lbl_zip.setText("")
        self.lbl_zip.setObjectName("lbl_zip")
        self.zip_layout.addWidget(self.lbl_zip)
        self.widget5 = QtWidgets.QWidget(self.centralwidget)
        self.widget5.setGeometry(QtCore.QRect(30, 390, 361, 33))
        self.widget5.setObjectName("widget5")
        self.email_layout = QtWidgets.QHBoxLayout(self.widget5)
        self.email_layout.setContentsMargins(0, 0, 0, 0)
        self.email_layout.setObjectName("email_layout")
        self.lbl_email_2 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_email_2.setFont(font)
        self.lbl_email_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_email_2.setObjectName("lbl_email_2")
        self.email_layout.addWidget(self.lbl_email_2)
        self.lbl_email = QtWidgets.QLabel(self.widget5)
        self.lbl_email.setMinimumSize(QtCore.QSize(231, 31))
        self.lbl_email.setMaximumSize(QtCore.QSize(231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_email.setFont(font)
        self.lbl_email.setText("")
        self.lbl_email.setObjectName("lbl_email")
        self.email_layout.addWidget(self.lbl_email)
        self.widget6 = QtWidgets.QWidget(self.centralwidget)
        self.widget6.setGeometry(QtCore.QRect(31, 120, 191, 33))
        self.widget6.setObjectName("widget6")
        self.id_layout = QtWidgets.QHBoxLayout(self.widget6)
        self.id_layout.setContentsMargins(0, 0, 0, 0)
        self.id_layout.setObjectName("id_layout")
        self.lbl_id_2 = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_id_2.setFont(font)
        self.lbl_id_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_id_2.setObjectName("lbl_id_2")
        self.id_layout.addWidget(self.lbl_id_2)
        self.lbl_id = QtWidgets.QLabel(self.widget6)
        self.lbl_id.setMinimumSize(QtCore.QSize(101, 31))
        self.lbl_id.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_id.setFont(font)
        self.lbl_id.setText("")
        self.lbl_id.setObjectName("lbl_id")
        self.id_layout.addWidget(self.lbl_id)
        self.widget7 = QtWidgets.QWidget(self.centralwidget)
        self.widget7.setGeometry(QtCore.QRect(420, 390, 341, 33))
        self.widget7.setObjectName("widget7")
        self.mobile_layout = QtWidgets.QHBoxLayout(self.widget7)
        self.mobile_layout.setContentsMargins(0, 0, 0, 0)
        self.mobile_layout.setObjectName("mobile_layout")
        self.lbl_mobile_2 = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_mobile_2.setFont(font)
        self.lbl_mobile_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_mobile_2.setObjectName("lbl_mobile_2")
        self.mobile_layout.addWidget(self.lbl_mobile_2)
        self.lbl_mobile = QtWidgets.QLabel(self.widget7)
        self.lbl_mobile.setMinimumSize(QtCore.QSize(191, 31))
        self.lbl_mobile.setMaximumSize(QtCore.QSize(191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_mobile.setFont(font)
        self.lbl_mobile.setText("")
        self.lbl_mobile.setObjectName("lbl_mobile")
        self.mobile_layout.addWidget(self.lbl_mobile)
        self.widget8 = QtWidgets.QWidget(self.centralwidget)
        self.widget8.setGeometry(QtCore.QRect(30, 460, 361, 33))
        self.widget8.setObjectName("widget8")
        self.emcontact_layout = QtWidgets.QHBoxLayout(self.widget8)
        self.emcontact_layout.setContentsMargins(0, 0, 0, 0)
        self.emcontact_layout.setObjectName("emcontact_layout")
        self.lbl_emContact_2 = QtWidgets.QLabel(self.widget8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_emContact_2.setFont(font)
        self.lbl_emContact_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_emContact_2.setObjectName("lbl_emContact_2")
        self.emcontact_layout.addWidget(self.lbl_emContact_2)
        self.lbl_emContact = QtWidgets.QLabel(self.widget8)
        self.lbl_emContact.setMinimumSize(QtCore.QSize(211, 31))
        self.lbl_emContact.setMaximumSize(QtCore.QSize(211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_emContact.setFont(font)
        self.lbl_emContact.setText("")
        self.lbl_emContact.setObjectName("lbl_emContact")
        self.emcontact_layout.addWidget(self.lbl_emContact)
        self.widget9 = QtWidgets.QWidget(self.centralwidget)
        self.widget9.setGeometry(QtCore.QRect(420, 460, 341, 33))
        self.widget9.setObjectName("widget9")
        self.emnumber_layout = QtWidgets.QHBoxLayout(self.widget9)
        self.emnumber_layout.setContentsMargins(0, 0, 0, 0)
        self.emnumber_layout.setObjectName("emnumber_layout")
        self.lbl_emNumber_2 = QtWidgets.QLabel(self.widget9)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_emNumber_2.setFont(font)
        self.lbl_emNumber_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_emNumber_2.setObjectName("lbl_emNumber_2")
        self.emnumber_layout.addWidget(self.lbl_emNumber_2)
        self.lbl_emNumber = QtWidgets.QLabel(self.widget9)
        self.lbl_emNumber.setMinimumSize(QtCore.QSize(161, 31))
        self.lbl_emNumber.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_emNumber.setFont(font)
        self.lbl_emNumber.setText("")
        self.lbl_emNumber.setObjectName("lbl_emNumber")
        self.emnumber_layout.addWidget(self.lbl_emNumber)
        self.widget10 = QtWidgets.QWidget(self.centralwidget)
        self.widget10.setGeometry(QtCore.QRect(30, 570, 331, 33))
        self.widget10.setObjectName("widget10")
        self.certification_layout = QtWidgets.QHBoxLayout(self.widget10)
        self.certification_layout.setContentsMargins(0, 0, 0, 0)
        self.certification_layout.setObjectName("certification_layout")
        self.lbl_certification_2 = QtWidgets.QLabel(self.widget10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_certification_2.setFont(font)
        self.lbl_certification_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_certification_2.setObjectName("lbl_certification_2")
        self.certification_layout.addWidget(self.lbl_certification_2)
        self.lbl_certification = QtWidgets.QLabel(self.widget10)
        self.lbl_certification.setMinimumSize(QtCore.QSize(191, 31))
        self.lbl_certification.setMaximumSize(QtCore.QSize(191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_certification.setFont(font)
        self.lbl_certification.setText("")
        self.lbl_certification.setObjectName("lbl_certification")
        self.certification_layout.addWidget(self.lbl_certification)
        self.widget11 = QtWidgets.QWidget(self.centralwidget)
        self.widget11.setGeometry(QtCore.QRect(420, 570, 311, 33))
        self.widget11.setObjectName("widget11")
        self.operator_layout = QtWidgets.QHBoxLayout(self.widget11)
        self.operator_layout.setContentsMargins(0, 0, 0, 0)
        self.operator_layout.setObjectName("operator_layout")
        self.lbl_operator_2 = QtWidgets.QLabel(self.widget11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_operator_2.setFont(font)
        self.lbl_operator_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_operator_2.setObjectName("lbl_operator_2")
        self.operator_layout.addWidget(self.lbl_operator_2)
        self.lbl_operator = QtWidgets.QLabel(self.widget11)
        self.lbl_operator.setMinimumSize(QtCore.QSize(211, 31))
        self.lbl_operator.setMaximumSize(QtCore.QSize(211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_operator.setFont(font)
        self.lbl_operator.setText("")
        self.lbl_operator.setObjectName("lbl_operator")
        self.operator_layout.addWidget(self.lbl_operator)
        self.widget12 = QtWidgets.QWidget(self.centralwidget)
        self.widget12.setGeometry(QtCore.QRect(261, 181, 191, 33))
        self.widget12.setObjectName("widget12")
        self.dob_layout = QtWidgets.QHBoxLayout(self.widget12)
        self.dob_layout.setContentsMargins(0, 0, 0, 0)
        self.dob_layout.setObjectName("dob_layout")
        self.lbl_dob_2 = QtWidgets.QLabel(self.widget12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_dob_2.setFont(font)
        self.lbl_dob_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_dob_2.setObjectName("lbl_dob_2")
        self.dob_layout.addWidget(self.lbl_dob_2)
        self.lbl_dob = QtWidgets.QLabel(self.widget12)
        self.lbl_dob.setMinimumSize(QtCore.QSize(81, 31))
        self.lbl_dob.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_dob.setFont(font)
        self.lbl_dob.setText("")
        self.lbl_dob.setObjectName("lbl_dob")
        self.dob_layout.addWidget(self.lbl_dob)
        self.widget13 = QtWidgets.QWidget(self.centralwidget)
        self.widget13.setGeometry(QtCore.QRect(31, 631, 241, 33))
        self.widget13.setObjectName("widget13")
        self.issuedate_layout = QtWidgets.QHBoxLayout(self.widget13)
        self.issuedate_layout.setContentsMargins(0, 0, 0, 0)
        self.issuedate_layout.setObjectName("issuedate_layout")
        self.lbl_issuedate_2 = QtWidgets.QLabel(self.widget13)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_issuedate_2.setFont(font)
        self.lbl_issuedate_2.setStyleSheet("color: rgb(68, 68, 68);")
        self.lbl_issuedate_2.setObjectName("lbl_issuedate_2")
        self.issuedate_layout.addWidget(self.lbl_issuedate_2)
        self.lbl_issuedate = QtWidgets.QLabel(self.widget13)
        self.lbl_issuedate.setMinimumSize(QtCore.QSize(81, 31))
        self.lbl_issuedate.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.lbl_issuedate.setFont(font)
        self.lbl_issuedate.setText("")
        self.lbl_issuedate.setObjectName("lbl_issuedate")
        self.issuedate_layout.addWidget(self.lbl_issuedate)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_cancel, self.btn_update)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AIDS – Pilot Profile [Administrator] "))
        self.lbl_caap.setText(_translate("MainWindow", "CAAP RPAS Certification Details"))
        self.btn_cancel.setText(_translate("MainWindow", "Back"))
        self.btn_pastops.setText(_translate("MainWindow", "Past Operations"))
        self.btn_update.setText(_translate("MainWindow", "Update"))
        self.lbl_expirydate_2.setText(_translate("MainWindow", "License Expiry Date :"))
        self.lbl_gender_2.setText(_translate("MainWindow", "Gender :"))
        self.lbl_address_2.setText(_translate("MainWindow", "Permanent Address :"))
        self.lbl_city_2.setText(_translate("MainWindow", "City :"))
        self.lbl_province_2.setText(_translate("MainWindow", "Province :"))
        self.lbl_zip_2.setText(_translate("MainWindow", "Zip Code :"))
        self.lbl_email_2.setText(_translate("MainWindow", "Email Address :"))
        self.lbl_id_2.setText(_translate("MainWindow", "ID No. :"))
        self.lbl_mobile_2.setText(_translate("MainWindow", "Phone Number :"))
        self.lbl_emContact_2.setText(_translate("MainWindow", "Emergency Contact :"))
        self.lbl_emNumber_2.setText(_translate("MainWindow", "Emergency Contact No. :"))
        self.lbl_certification_2.setText(_translate("MainWindow", "Certification No. :"))
        self.lbl_operator_2.setText(_translate("MainWindow", "Operator :"))
        self.lbl_dob_2.setText(_translate("MainWindow", "Date of Birth :"))
        self.lbl_issuedate_2.setText(_translate("MainWindow", "License Issue Date :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
